Pr update mocks
SAP/stewardci-core pull request #208
Opened 2021-02-03 09:45 UTC by rinckm

### Description

Add update-mocks script

### Submitter checklist

- [ ] Change has been tested (on a back-end cluster)
- [ ] (If applicable) Jira backlog item ID added to the PR title and the [changelog.yaml] entry
- [ ] [changelog.yaml] entry with upgrade notes is prepared and appropriate for the audience affected by the change (users or developer, depending on the change)
- [ ] Semantic version diffed against [last release][releases] and updated accordingly. In this project the version has to be maintained here:
    - [/charts/steward/Chart.yaml](https://github.com/SAP/stewardci-core/blob/master/charts/steward/Chart.yaml) (`version` and `appVersion`)

In case dependencies have been updated:
- [ ] Links to external changelogs, since the last release of our component, added to the [changelog.yaml] entry (description).
- [ ] Changelogs read thoroughly, potential impact described, upgrade notes prepared (if necessary)
- [ ] Check if dependency updates affect our semantic version increment.

### Reviewer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There is at least 1 approval for the pull request and no outstanding requests for change
- [ ] All voter checks have passed
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] The Pull Request title is understandable and reflects the changes well
- [ ] The Pull Request description is understandable and well documented
- [ ] [changelog.yaml] entry for this Pull Request has been added
    - [ ] Changelog entry contains all required information
    - [ ] 'Upgrade notes' are documented in changelog.yaml (if required)

[changelog.yaml]: https://github.com/SAP/stewardci-core/changelog.yaml
[releases]: https://github.com/SAP/stewardci-core/releases

2021-02-15 11:30 UTC, anbrsap requested changes
The script duplicates many parts of `hack/update-codegen.sh`, which violates the DRY principle. Also refactor `hack/update-codegen.sh` to avoid code duplication.

2021-02-15 13:12 UTC, rinckm commented on changelog.yaml
> +      Add a script to regenerate the mocks without regeneration all clients.
```suggestion
  - type: internal
    impact: patch
    title: "Add only-mocks mode to the codegen script"
    description: |-
      Add a mode to only regenerate the mocks without regeneration all clients.
```

2021-02-17 13:22 UTC, anbrsap commented on hack/update-codegen.sh
> +		;;
Indentation is inconsistent.

2021-02-17 13:22 UTC, anbrsap commented on hack/update-codegen.sh
> +    echo ""
```suggestion
    echo "  -m, --only-mocks"
    echo "      Only regenerate mocks."
    echo ""
```

2021-02-17 13:22 UTC, anbrsap commented on hack/update-codegen.sh
> +    echo "  -m, --only-mocks"
The "only XXX" approach makes it impossible to select more than one type.

I propose to call this option `--mocks`. In the future we could add further options to select other types, e.g. `--tekton-client`. You can combine those options to generate more than one type but not all. If none of those options is specified, all types get generated.

2021-02-18 08:37 UTC, anbrsap approved these changes

2021-02-18 08:37 UTC, anbrsap commented
**Squash before merge!**

2021-02-18 09:29 UTC, rinckm commented on changelog.yaml
> +    title: [Developer] update-codegen.sh: make generators selectable
```suggestion
    title: "[Developer] update-codegen.sh: make generators selectable"
```

2021-02-18 09:54 UTC, merged