Add namespace lister
SAP/stewardci-core pull request #215
Opened 2021-02-16 14:58 UTC by LenaHoinkis

### Description

&lt;Add detailed description for reviewers here.&gt;

### Submitter checklist

- [ ] Change has been tested (on a back-end cluster)
- [ ] (If applicable) Jira backlog item ID added to the PR title and the [changelog.yaml] entry
- [ ] [changelog.yaml] entry with upgrade notes is prepared and appropriate for the audience affected by the change (users or developer, depending on the change)
- [ ] Semantic version diffed against [last release][releases] and updated accordingly. In this project the version has to be maintained here:
    - [/charts/steward/Chart.yaml](https://github.com/SAP/stewardci-core/blob/master/charts/steward/Chart.yaml) (`version` and `appVersion`)

In case dependencies have been updated:
- [ ] Links to external changelogs, since the last release of our component, added to the [changelog.yaml] entry (description).
- [ ] Changelogs read thoroughly, potential impact described, upgrade notes prepared (if necessary)
- [ ] Check if dependency updates affect our semantic version increment.

### Reviewer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There is at least 1 approval for the pull request and no outstanding requests for change
- [ ] All voter checks have passed
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] The Pull Request title is understandable and reflects the changes well
- [ ] The Pull Request description is understandable and well documented
- [ ] [changelog.yaml] entry for this Pull Request has been added
    - [ ] Changelog entry contains all required information
    - [ ] 'Upgrade notes' are documented in changelog.yaml (if required)

[changelog.yaml]: https://github.com/SAP/stewardci-core/changelog.yaml
[releases]: https://github.com/SAP/stewardci-core/releases

2021-02-17 14:52 UTC, anbrsap commented on pkg/tenantctl/controller_test.go
> +	defer stopController(t, stopCh)
I don't like that the controller gets started for those tests where we explicitly call e.g. `syncHandler()`.
Instead, just _create_ the controller as before and start `cf.CoreV1InformerFactory()` in addition.

You may use a helper function that returns a deferrable stop function:

```go
ctl := NewController(cf, NewMetrics())
defer startCoreV1Informer(ctl)()
```

```go
func startCoreV1Informer(ctl *Controller) func() {
	stopCh := make(chan struct{}, 0)
	ctl.factory.CoreV1InformerFactory().Start(stopCh)
	return func() {
		stopCh <- struct{}{}
	}
}
```

2021-02-18 12:01 UTC, rinckm commented on pkg/k8s/fake/clientFactory.go
> +	//kubernetesInformerFactory := informers.NewSharedInformerFactory(kubernetesClientset, time.Minute*10)
```suggestion
```

2021-02-18 12:02 UTC, rinckm commented on pkg/k8s/fake/clientFactory.go
> +func (f *ClientFactory) KubernetesInterface() kubernetesTrue.Interface {
Please add docu

2021-02-23 11:11 UTC, rinckm commented on pkg/k8s/fake/clientFactory.go
>  	kubernetes "k8s.io/client-go/kubernetes/fake"
Maybe you should rename to kubernetes and kubernetesfake

2021-02-23 11:14 UTC, rinckm commented on pkg/k8s/fake/clientFactory.go
> +// KubernetesClientset returns an interface of the Kubernetes fake clientset.
```suggestion
// KubernetesInterface returns an interface of the Kubernetes fake clientset.
```

2021-02-23 13:03 UTC, anbrsap commented on pkg/k8s/clientFactory.go
> +	KubernetesInterface() kubernetes.Interface
I would use the name `KubernetesClientSet()` instead, as package `k8s.io/client-go/kubernetes` provides the Kubernetes client set, and `Interface` is just a _local_ name from this package.

2021-05-25 08:56 UTC, jia-jerry requested changes

2021-05-25 08:56 UTC, jia-jerry commented on pkg/tenantctl/controller.go
> +	c.namespaceFactory.Start(stopCh)
To be consistent, please puth the informerfactor `Start` with https://github.com/SAP/stewardci-core/blob/master/cmd/run_controller/main.go#L78

2023-06-12 12:00 UTC, closed without merging